const IMAGE = {
    // CustomHeader.js
    ICON_MENU : require('../images/menu.png'),
    ICON_BACK : require('../images/back.png'),

    //navigator.js
    ICON_HOME1 : require('../images/home1.png'),
    ICON_HOME2 : require('../images/home2.png'),
    ICON_MAP1 : require('../images/map.png'),
    ICON_MAP2 : require('../images/map-2.png'),
    ICON_NEW1 : require('../images/new.png'),
    ICON_NEW2 : require('../images/new2.png'),
    ICON_INFO1 : require('../images/info.png'),
    ICON_INFO2 : require('../images/info-2.png'),

    //Other
    IMAGE_SYMPTOMPS1 : require('../images/symptomps1.png'),
    IMAGE_SYMPTOMPS2 : require('../images/symptomps2.png'),
    IMAGE_SYMPTOMPS3 : require('../images/symptomps3.png'),
    IMAGE_SYMPTOMPS4 : require('../images/symptomps4.png'),
    IMAGE_SYMPTOMPS5 : require('../images/symptomps5.png'),
    IMAGE_SYMPTOMPS6 : require('../images/symptomps6.png'),
    IMAGE_SYMPTOMPS7 : require('../images/symptomps7.png'),
    IMAGE_SYMPTOMPS8 : require('../images/symptomps8.png'),

    //Preventtion
    IMAGE_PREVENTION1 : require('../images/prevention1.png'),
    IMAGE_PREVENTION2 : require('../images/prevention2.png'),
    IMAGE_PREVENTION3 : require('../images/prevention3.png'),
    IMAGE_PREVENTION4 : require('../images/prevention4.png'),
    IMAGE_PREVENTION5 : require('../images/prevention5.png'),
    IMAGE_PREVENTION6 : require('../images/prevention6.png'),
    IMAGE_PREVENTION7 : require('../images/prevention7.png'),

    IMAGE_EVA : require('../images/eva.jpg'),

    IMAGE_THCHANA : require('../images/thai.png'),

    IMAGE_REPORT : require('../images/report.png'),

    //จังหวัด		
    IMAGE_ฺฺBKK : require('../images/bangkok.jpg'),		
    IMAGE_CBI : require('../images/chonburi.jpg'),		
    IMAGE_CPM : require('../images/phuket.jpg'),		
    IMAGE_SPK : require('../images/SamutPrakan.jpg'),		
    IMAGE_NBI : require('../images/Nonthaburi.jpg'),		
    IMAGE_YLA : require('../images/Yala.png'),		
    IMAGE_SKA : require('../images/Songkhla.jpg'),		
    IMAGE_PTN : require('../images/Pattani.jpg'),		
    IMAGE_NWT : require('../images/Narathiwat.jpeg'),		
    IMAGE_CMI : require('../images/ChiangMai.jpg'),		
    IMAGE_PTE : require('../images/PathumThani.jpg'),		
    IMAGE_CCO : require('../images/Chachoengsao.jpg'),		
    IMAGE_NPT : require('../images/NakhonPathom.png'),		
    IMAGE_CPN : require('../images/Chumphon.jpg'),		
    IMAGE_KBI : require('../images/Krabi.jpg'),		
    IMAGE_NMA : require('../images/NakhonRatchasima.jpg'),		
    IMAGE_SNI : require('../images/SuratThani.jpg'),		
    IMAGE_STN : require('../images/Satun.jpg'),		
    IMAGE_PKN : require('../images/Prachuap.jpg'),		
    IMAGE_UBN : require('../images/Ubon.jpg'),		
    IMAGE_PLG : require('../images/Phatthalung.jpg'),		
    IMAGE_SKN : require('../images/SamutSakhon.jpg'),		
    IMAGE_BRM : require('../images/Buriram.jpg'),		
    IMAGE_NST : require('../images/NST.jpg'),		
    IMAGE_UDN : require('../images/Udon.jpg'),		
    IMAGE_SKW : require('../images/SaKaeo.jpg'),		
    IMAGE_PRI : require('../images/Prachinburi.jpg'),		
    IMAGE_KRI : require('../images/Kan.jpg'),		
    IMAGE_SRN : require('../images/Surin.jpg'),		
    IMAGE_CRI : require('../images/ChiangRai.jpg'),		
    IMAGE_NSN : require('../images/NakhonSawan.jpg'),		
    IMAGE_SSK : require('../images/Sisaket.jpg'),		
    IMAGE_TRG : require('../images/Trang.jpg'),		
    IMAGE_RBR : require('../images/Ratchaburi.jpg'),		
    IMAGE_PLK : require('../images/Phitsanulok.jpg'),		
    IMAGE_KKN : require('../images/KhonKaen.jpg'),		
    IMAGE_SPB : require('../images/Suphan.jpg'),		
    IMAGE_RYG : require('../images/Rayong.jpg'),		
    IMAGE_LEI : require('../images/Loei.jpg'),		
    IMAGE_MSN : require('../images/MSN.jpg'),		
    IMAGE_SRI : require('../images/Saraburi.jpg'),		
    IMAGE_MDH : require('../images/Mukdahan.jpg'),		
    IMAGE_AYA : require('../images/AYA.jpg'),		
    IMAGE_LPN : require('../images/Lamphun.jpg'),		
    IMAGE_LPG : require('../images/Lampang.jpg'),		
    IMAGE_PNB : require('../images/Phetchabun.jpg'),		
    IMAGE_STI : require('../images/Sukhothai.jpg'),		
    IMAGE_UTT : require('../images/Uttaradit.jpg'),		
    IMAGE_CTI : require('../images/Chanthaburi.jpg'),		
    IMAGE_RET : require('../images/RoiEt.jpg'),		
    IMAGE_TAK : require('../images/Tak.jpg'),		
    IMAGE_NBP : require('../images/NBP.jpg'),		
    IMAGE_NKI : require('../images/NongKhai.jpg'),		
    IMAGE_CPM : require('../images/Chaiyaphum.jpg'),		
    IMAGE_PYO : require('../images/Phayao.jpg'),		
    IMAGE_KSN : require('../images/Kalasin.jpg'),		
    IMAGE_NYK : require('../images/NakhonNayok.jpg'),		
    IMAGE_ACR : require('../images/ACR.jpg'),		
    IMAGE_PNA : require('../images/PhangNga.jpg'),		
    IMAGE_LRI : require('../images/Lopburi.jpg'),		
    IMAGE_NPT : require('../images/NPT.jpg'),		
    IMAGE_PBI : require('../images/Phetchaburi.jpg'),		
    IMAGE_PRE : require('../images/Phrae.jpg'),		
    IMAGE_YST : require('../images/Yasothon.jpg'),		
    IMAGE_UTI : require('../images/Uthai.jpg'),		
    IMAGE_SKM : require('../images/Songkhram.jpg'),		
    IMAGE_SKN : require('../images/SKN.jpg'),		
    IMAGE_MKM : require('../images/MKM.jpg'),

}
export {IMAGE}